AWSTemplateFormatVersion: 2010-09-09
Description: |
  This is a template for AWS CodePipeline
Parameters:
  0ptionalSuggestedStackName:
    Type: String
    Default: AWS-Codepipeline-Project-Stack
    Description: Copy this parameter to use it like the stack name.
  CodePipelineName:
    Type: String
    Default: pipeline_name
    Description: Codepipeline Name
  RepositoryName:
    Type: String
    Default: repo_name
    Description: Repository Name 
  CodeBuildProjectName:
    Type: String
    Default: build_project_name
    Description: Project name 
Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref CodePipelineName
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit # o cualquier otro proveedor de código fuente de CodePipeline
                Version: 1
              OutputArtifacts:
                - Name: source
              Configuration:
                RepositoryName: !Ref RepositoryName
                BranchName: main
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: source
              OutputArtifacts:
                - Name: build
              Configuration:
                ProjectName: !Ref CodeBuildProjectName
Outputs:
  CodePipelineExecutionRole:
    Value: !GetAtt CodePipeline.RoleArn