  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: CDN for S3-backed website
        Aliases:
          - !Join [
              "",
              [
                !Ref "AWS::StackName",
                !Ref "AWS::AccountId",
                .,
                !Ref "AWS::Region",
                .,
                !Ref "HostedZone",
              ],
            ]
        Enabled: "true"
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: "true"
          TargetOriginId: only-origin
          ViewerProtocolPolicy: allow-all
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:809489680864:certificate/540970d9-3fa5-4904-a28c-f4493fb9de27
          SslSupportMethod: vip
        DefaultRootObject: index.html
        Origins:
          - CustomOriginConfig:
              HTTPPort: "80"
              HTTPSPort: "443"
              OriginProtocolPolicy: http-only
            DomainName:
              !Join [
                "",
                [
                  !Ref "S3BucketWebsiteContent",
                  !FindInMap [
                    Region2S3WebsiteSuffix,
                    !Ref "AWS::Region",
                    Suffix,
                  ],
                ],
              ]
            Id: only-origin