AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation template to create a cloudfront distribution
Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3BucketOrigin
            DomainName: mcamachodev.com.s3.amazonaws.com
            S3OriginConfig: {}
        Aliases:
          - mcamachodev.info
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:809489680864:certificate/4b61e547-976c-45c6-b4fb-9d1c78834bf0
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          TargetOriginId: S3BucketOrigin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        Enabled: true
Outputs:
  CloudfrontDomain:
    Description: The domain name of the cloudfront distribution
    Value: !GetAtt CloudFrontDistribution.DomainName

