AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    IAMRole:
        Type: "AWS::IAM::Role"
        Properties:
            Path: "/"
            RoleName: "CodeDeployRole"
            AssumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"codedeploy.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
            MaxSessionDuration: 3600
            ManagedPolicyArns: 
              - "arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole"
            Description: "Allows CodeDeploy to call AWS services such as Auto Scaling on your behalf."

    CodeDeployApplication:
        Type: "AWS::CodeDeploy::Application"
        Properties:
            ApplicationName: "CodeDeployDemo"
            ComputePlatform: "Server"

    CodeDeployDeploymentGroup:
        Type: "AWS::CodeDeploy::DeploymentGroup"
        Properties:
            ApplicationName: !Ref CodeDeployApplication
            DeploymentGroupName: "MyDevelopmentInstances"
            DeploymentConfigName: "CodeDeployDefault.AllAtOnce"
            ServiceRoleArn: !GetAtt IAMRole.Arn
            AlarmConfiguration: 
                Enabled: false
                IgnorePollAlarmFailure: false
            DeploymentStyle: 
                DeploymentType: "IN_PLACE"
                DeploymentOption: "WITHOUT_TRAFFIC_CONTROL"
            Ec2TagSet: {}
            OnPremisesTagSet: {}

