AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: mcamachodev.info
            Id: mcamachodev-info
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: mcamachodev-info
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: true
        Aliases:
          - mcamachodev.info
        Enabled: true
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: mcamachodev.info
  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: mcamachodev.info
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: !Ref HostedZone 
