AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Cloudformation template to create a Codecommit respositry
Parameters:
  RepositoryName: 
Resources:
  Repository_resource:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: MyDemoRepo
      RepositoryDescription: This is a repository for my project with code from MySourceCodeBucket.
      Code:
        BranchName: development
        S3:
          Bucket: MySourceCodeBucket
          Key: MyKey
          ObjectVersion: 1

Outputs:
